version: 1
datastore:
  user: user
  password: password
  hostname: acit3855-hosung.westus3.cloudapp.azure.com
  port: 3306
  db: events
events: 
  hostname: acit3855-hosung.westus3.cloudapp.azure.com
  port: 9092 
  topic: events
  max_retries: 10
  sleep: 2